{{- if .Values.mysql.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "2-tier-app.fullname" . }}-mysql
  labels:
    {{- include "2-tier-app.mysql.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels:
      {{- include "2-tier-app.mysql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "2-tier-app.mysql.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: mysql
        image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
        imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.mysql.service.port }}
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "2-tier-app.fullname" . }}-mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ include "2-tier-app.fullname" . }}-mysql-secret
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "2-tier-app.fullname" . }}-mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "2-tier-app.fullname" . }}-mysql-secret
              key: MYSQL_PASSWORD
        {{- if .Values.mysql.persistence.enabled }}
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        {{- end }}
        resources:
          {{- toYaml .Values.mysql.resources | nindent 10 }}
      {{- if .Values.mysql.persistence.enabled }}
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: {{ include "2-tier-app.fullname" . }}-mysql-pvc
      {{- end }}
{{- end }}
