{{- if .Values.webapp.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "2-tier-app.fullname" . }}-webapp
  labels:
    {{- include "2-tier-app.webapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webapp.replicas }}
  selector:
    matchLabels:
      {{- include "2-tier-app.webapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "2-tier-app.webapp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: webapp
        image: "{{ .Values.webapp.image.repository }}:{{ .Values.webapp.image.tag }}"
        imagePullPolicy: {{ .Values.webapp.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.webapp.service.targetPort }}
          name: http
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ include "2-tier-app.fullname" . }}-webapp-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ include "2-tier-app.fullname" . }}-webapp-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ include "2-tier-app.fullname" . }}-webapp-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "2-tier-app.fullname" . }}-mysql-secret
              key: MYSQL_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "2-tier-app.fullname" . }}-mysql-secret
              key: MYSQL_PASSWORD
        resources:
          {{- toYaml .Values.webapp.resources | nindent 10 }}
        {{- if .Values.webapp.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.webapp.livenessProbe.httpGet.path }}
            port: {{ .Values.webapp.livenessProbe.httpGet.port }}
          initialDelaySeconds: {{ .Values.webapp.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.webapp.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.webapp.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.webapp.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.webapp.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.webapp.readinessProbe.httpGet.path }}
            port: {{ .Values.webapp.readinessProbe.httpGet.port }}
          initialDelaySeconds: {{ .Values.webapp.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.webapp.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.webapp.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.webapp.readinessProbe.failureThreshold }}
        {{- end }}
{{- end }}
